name: Build rime deployer
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary_name: rime_deployer
          - os: ubuntu-24.04-arm
            binary_name: rime_deployer-arm64

    steps:
      - name: Get librime version
        run: echo "LIBRIME_VERSION=$(cat .librime-version)" >> $GITHUB_ENV

      - name: Checkout librime
        uses: actions/checkout@v7
        with:
          repository: rime/librime
          ref: ${{ env.LIBRIME_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libboost-regex-dev libleveldb-dev libmarisa-dev libyaml-cpp-dev libopencc-dev

      - name: Build
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DENABLE_LOGGING=OFF -DBUILD_TEST=OFF
          cmake --build build
          g++ -I src -I build/src -o ${{ matrix.binary_name }} tools/rime_deployer.cc build/lib/librime.a -lmarisa -lleveldb -lopencc -lyaml-cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.binary_name }}
          path: ${{ matrix.binary_name }}

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            rime_deployer*
